### ISSUE TITLE
Error during using this repo

### ISSUE THREAD

**Issue by sursunpan** [alexa-labs/skill-sample-alexa-for-apps#4]
1. During updating manifest skill i got an error
[Error]: {
  "message": "Server cannot process the request due to a client error.",
  "stack": "ServiceError: Server cannot process the request due to a client error.\n    at SkillManagementServiceClient.<anonymous> (/home/suraj/.nvm/versions/node/v17.5.0/lib/node_modules/ask-cli/node_modules/ask-sdk-model-runtime/dist/index.js:335:31)\n    at step (/home/suraj/.nvm/versions/node/v17.5.0/lib/node_modules/ask-cli/node_modules/ask-sdk-model-runtime/dist/index.js:58:23)\n    at Object.next (/home/suraj/.nvm/versions/node/v17.5.0/lib/node_modules/ask-cli/node_modules/ask-sdk-model-runtime/dist/index.js:39:53)\n    at fulfilled (/home/suraj/.nvm/versions/node/v17.5.0/lib/node_modules/ask-cli/node_modules/ask-sdk-model-runtime/dist/index.js:30:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
  "detail": {
    "name": "ServiceError",
    "statusCode": 400,
    "headers": [
      {
        "key": "content-type",
        "value": "application/json"
      },
      {
        "key": "content-length",
        "value": "575"
      },
      {
        "key": "connection",
        "value": "close"
      },
      {
        "key": "server",
        "value": "Server"
      },
      {
        "key": "date",
        "value": "Wed, 28 Sep 2022 03:13:15 GMT"
      },
      {
        "key": "x-amz-rid",
        "value": "ZZ6ERC72ZE7HXCXCWXGM"
      },
      {
        "key": "x-amzn-requestid",
        "value": "01b852a9-496d-4d3c-af3a-b49860903b57"
      },
      {
        "key": "x-amz-date",
        "value": "Wed, 28 Sep 2022 03:13:15 GMT"
      },
      {
        "key": "vary",
        "value": "Content-Type,Accept-Encoding,User-Agent"
      },
      {
        "key": "x-cache",
        "value": "Error from cloudfront"
      },
      {
        "key": "via",
        "value": "1.1 62e8a6c4e8bc177af56566455e45c7a2.cloudfront.net (CloudFront)"
      },
      {
        "key": "x-amz-cf-pop",
        "value": "DEL51-P4"
      },
      {
        "key": "x-amz-cf-id",
        "value": "RLACXTt7Puhd2NNa9iAJVzkujHwnxioAFtNxflOhSs09j1aSo4wdCw=="
      }
    ],
    "response": {
      "message": "Skill manifest is not valid.",
      "violations": [
        {
          "code": "DENIED_FEATURE_ACCESS",
          "message": "User is not allowed access to the \"AppLink V2\" feature and, therefore, cannot use string instance with value \"\"APP_LINKS_V2\"\" at \"$.manifest.apis.custom.interfaces[0].type\". Further information: \"alexaforapps-help@amazon.com\".",
          "validationDetails": {
            "feature": {
              "contact": "alexaforapps-help@amazon.com",
              "name": "AppLink V2"
            },
            "originalInstance": {
              "dataType": "string",
              "propertyPath": "$.manifest.apis.custom.interfaces[0].type",
              "type": "BODY",
              "value": "\"APP_LINKS_V2\""
            }
          }
        }
      ]
    }
  }
}
2. During deploy i got an error
[Error]: {
  "skill": {
    "eTag": "2cd8e03027fae2e750b3a5be9a44fd6c",
    "resources": [
      {
        "action": "UPDATE",
        "errors": [
          {
            "message": "User is not allowed access to the \"AppLink V2\" feature and, therefore, cannot use string instance with value \"\"APP_LINKS_V2\"\" at \"$.manifest.apis.custom.interfaces[0].type\". Further information: \"alexaforapps-help@amazon.com\"."
          }
        ],
        "name": "Manifest",
        "status": "FAILED"
      }
    ],
    "skillId": "amzn1.ask.skill.be688796-a772-44dc-bc38-bfb20f9de694"
  },
  "status": "FAILED"
}

please try to resolve my issue fast

**Comment by markapeters** [comment]
Hi - Did you ever figure this problem out? I'm having the same problem with my first attempt at creating a skill to interact with my Android app.

**Comment by sursunpan** [comment]
Hi- I think this problem was solved.but this my first office client project which I left  now. I totally forgot about. But i try my best to give solution.

**Comment by markapeters** [comment]
Thanks - if you can recall that, it would be very helpful! The docs are way out of date, especially for configuring Amazon's IAM - I suspect that something is mis-configured there.
